###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    memcached:
      image: memcached:alpine
      container_name: steamwheedle-api-memcached

    redis:
      image: redis:alpine
      container_name: steamwheedle-api-redis

    mysql:
      image: mysql:5.7
      container_name: steamwheedle-api-mysql
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=steamwheedle
        - MYSQL_DATABASE=steamwheedle
        - MYSQL_USER=steamwheedle
        - MYSQL_PASSWORD=steamwheedle
      ports:
        - "8082:3306"

    webserver:
      image: nginx:alpine
      container_name: steamwheedle-api-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8080:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: steamwheedle-api-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini

